analyzer:
  exclude: [lib/gen/**]
  language:
    strict-raw-types: true
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    await_only_futures: error
    unawaited_futures: error
    avoid_void_async: error
    avoid_returning_null_for_future: error
    unrelated_type_equality_checks: error
    iterable_contains_unrelated_type: error
    list_remove_unrelated_type: error

linter:
  rules:
    ## EFFECTIVE DART ##
    # STYLE
    - camel_case_types
    - camel_case_extensions
    - library_names
    - file_names
    #- library_prefixes
    - non_constant_identifier_names
    - constant_identifier_names # prefer
    - directives_ordering
    #- lines_longer_than_80_chars # avoid
    - curly_braces_in_flow_control_structures
    - prefer_single_quotes

    # DOCUMENTATION
    - slash_for_doc_comments
    #- package_api_docs # prefer
    #- public_member_api_docs # prefer
    #- comment_references # Unused because https://github.com/dart-lang/sdk/issues/36974

    # USAGE
    - implementation_imports
    - avoid_relative_lib_imports
    #- prefer_relative_imports
    - prefer_adjacent_string_concatenation
    - prefer_interpolation_to_compose_strings # prefer
    - unnecessary_brace_in_string_interps # avoid
    - prefer_collection_literals
    - prefer_is_empty
    - prefer_is_not_empty
    - avoid_function_literals_in_foreach_calls # avoid
    - prefer_iterable_whereType
    - prefer_function_declarations_over_variables
    - unnecessary_lambdas
    - prefer_equal_for_default_values
    - avoid_init_to_null
    - unnecessary_getters_setters
    #- unnecessary_getters # prefer # Disabled pending fix: https://github.com/dart-lang/linter/issues/23
    #- prefer_expression_function_bodies # consider
    - unnecessary_this
    - prefer_initializing_formals
    - type_init_formals
    - empty_constructor_bodies
    - unnecessary_new
    - unnecessary_const
    #- avoid_catches_without_on_clauses # avoid
    - avoid_catching_errors
    - use_rethrow_when_possible

    # DESIGN
    #- use_to_and_as_if_applicable # prefer
    #- one_member_abstracts # avoid
    #- avoid_classes_with_only_static_members # avoid
    #- prefer_mixin
    - prefer_final_fields # prefer
    - prefer_final_locals
    - prefer_final_in_for_each
    - use_setters_to_change_properties
    #- avoid_setters_without_getters
    #- avoid_returning_null # avoid
    - avoid_returning_this # avoid
    - type_annotate_public_apis # prefer
    - prefer_typing_uninitialized_variables # consider
    - omit_local_variable_types # avoid
    #- avoid_types_on_closure_parameters # avoid
    - avoid_return_types_on_setters
    - prefer_generic_function_type_aliases
    - avoid_private_typedef_functions # prefer
    #- use_function_type_syntax_for_parameters # consider
    #- avoid_positional_boolean_parameters # avoid
    - hash_and_equals
    - avoid_equals_and_hash_code_on_mutable_classes # avoid
    - avoid_null_checks_in_equality_operators

    ## PEDANTIC ##
    - always_declare_return_types
    - always_require_non_null_named_parameters
    - annotate_overrides
    - avoid_shadowing_type_parameters
    - avoid_single_cascade_in_expression_statements
    - avoid_types_as_parameter_names
    - await_only_futures
    - empty_catches
    - no_duplicate_case_values
    - null_closures
    - prefer_conditional_assignment
    - prefer_contains
    - prefer_for_elements_to_map_fromIterable
    - prefer_if_null_operators
    - prefer_inlined_adds
    - prefer_spread_collections
    - recursive_getters
    - sort_child_properties_last
    - unawaited_futures
    - unnecessary_null_in_if_null_operators
    - unrelated_type_equality_checks
    - unsafe_html
    - use_full_hex_values_for_flutter_colors
    - use_function_type_syntax_for_parameters
    - valid_regexps

    ##CUSTOM
    - avoid_void_async
    - unnecessary_await_in_return

    #NEW
    - avoid_dynamic_calls
    - avoid_returning_null_for_future
    - avoid_slow_async_io
    - avoid_type_to_string
    #- avoid_web_libraries_in_flutter
    - cancel_subscriptions
    - close_sinks
    - invariant_booleans
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - literal_only_boolean_expressions
    - prefer_void_to_null
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_statements
    - use_build_context_synchronously
    #- avoid_annotating_with_dynamic
    - avoid_bool_literals_in_conditional_expressions
    - avoid_implementing_value_types
    - avoid_js_rounded_ints
    - avoid_returning_null_for_void
    - cast_nullable_to_non_nullable
    #- do_not_use_environment
    - join_return_with_assignment
    - missing_whitespace_between_adjacent_strings
    - no_runtimeType_toString
    - null_check_on_nullable_type_parameter
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - sized_box_for_whitespace
    - unnecessary_null_aware_assignments
    - unnecessary_null_checks
    #Flutter lints
    - avoid_print
    - avoid_unnecessary_containers
    - avoid_web_libraries_in_flutter
    - no_logic_in_create_state
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    #- use_key_in_widget_constructors
