targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - implicit_dynamic_parameter
            - type_annotate_public_apis
      functional_widget:
        options:
          debugFillProperties: true
      mek_data_class_generator|data_class:
        enabled: true
        options:
          pageWidth: 80
          comparable: false
          stringify: true
          copyable: true
          changeable: false
          changesVisible: false