name: wcs_mobil
description: WCS Mobil

publish_to: 'none'

version: 1.0.0+0

environment:
  sdk: '>=2.18.6'
  flutter: '>=3.3.10'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.0
  async: ^2.10.0
  collection: ^1.16.0
  shimmer: ^2.0.0
  dio: ^4.0.6
  awesome_dio_interceptor: ^0.0.2+4
  retrofit: ^3.3.1
  go_router: ^6.0.1
  json_annotation: ^4.7.0
  mek_data_class: ^1.0.0
  storybook_flutter: ^0.11.3
  flutter_custom_tabs: ^1.0.4
  country: ^2.0.5
  functional_widget_annotation: ^0.10.0
  flutter_bloc: ^8.1.1

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.5.4
  retrofit_generator: ^4.2.0
  mek_data_class_generator: ^1.0.0
  functional_widget: ^0.10.1

flutter:
  uses-material-design: true